Traceback (most recent call last):
  File "/kunden/homepages/8/d657042007/htdocs/CodeSet/private_server/guard/CELL-33/Q-32/33-32.py", line 4, in <module>
    print(int(now))
TypeError: int() argument must be a string or a number, not 'datetime.datetime'
